services:
  postgres:
    image: postgres:17.5
    container_name: local_test_db
    environment:
      POSTGRES_DB: local_test_db
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    volumes:
      - template_liquibase_migration_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - "local_test_network"

networks:
  local_test_network:
    driver: bridge

volumes:
  template_liquibase_migration_volume:
    driver: local